// retcode.js
/*
 * This is an auto-generated source file.
 */

var RetCode = {
	'RETCODE_OK': 0,
	'RETCODE_KO': 1,
	'RETCODE_KO_NULL_REQ_SOURCE': 2,
	'RETCODE_KO_UNKNOWN_REQ_SOURCE': 3,
	'RETCODE_KO_LOGIN_FAILED': 4,
	'RETCODE_KO_NOTLOGIN_OR_TIMEOUT': 5,
	'RETCODE_KO_DB_OPEN_CONN_FAILED': 6,
	'RETCODE_KO_DB_CLOSE_CONN_FAILED': 7,
	'RETCODE_KO_DB_CREATE_STMT_FAILED': 8,
	'RETCODE_KO_DB_CLOSE_STMT_FAILED': 9,
	'RETCODE_KO_UNKNOWN_DB_ACTION': 10,
	'RETCODE_KO_MANAGE_SCHOOL_NULL_ACTION': 11,
	'RETCODE_KO_MANAGE_SCHOOL_NULL_NAME': 12,
	'RETCODE_KO_MANAGE_SCHOOL_SELECT_FAILED': 13,
	'RETCODE_KO_MANAGE_SCHOOL_INSERT_FAILED': 14,
	'RETCODE_KO_MANAGE_SCHOOL_UPDATE_FAILED': 15,
	'RETCODE_KO_MANAGE_SCHOOL_DELETE_FAILED': 16,
	'RETCODE_KO_MANAGE_TEACHER_NULL_ACTION': 17,
	'RETCODE_KO_MANAGE_TEACHER_SELECT_FAILED': 18,
	'RETCODE_KO_MANAGE_TEACHER_INSERT_FAILED': 19,
	'RETCODE_KO_MANAGE_TEACHER_UPDATE_FAILED': 20,
	'RETCODE_KO_MANAGE_TEACHER_DELETE_FAILED': 21,
	'RETCODE_KO_MANAGE_CLASS_TABLES_NULL_ACTION': 22,
	'RETCODE_KO_MANAGE_CLASS_TABLES_NULL_SCHOOLID': 23,
	'RETCODE_KO_MANAGE_CLASS_TABLES_SELECT_FAILED': 24
};

// End of file
