package com.ajh.futurestar.common;

public enum RetCode {
	RETCODE_OK,
	RETCODE_KO,
	RETCODE_KO_NULL_REQ_SOURCE,
	RETCODE_KO_UNKNOWN_REQ_SOURCE,
	RETCODE_KO_LOGIN_FAILED,
	RETCODE_KO_NOTLOGIN_OR_TIMEOUT,
	RETCODE_KO_DB_OPEN_CONN_FAILED,
	RETCODE_KO_DB_CLOSE_CONN_FAILED,
	RETCODE_KO_DB_CREATE_STMT_FAILED,
	RETCODE_KO_DB_CLOSE_STMT_FAILED,
	RETCODE_KO_UNKNOWN_DB_ACTION,
	RETCODE_KO_MANAGE_SCHOOL_NULL_NAME,
	RETCODE_KO_MANAGE_SCHOOL_INSERT_FAILED,
	RETCODE_KO_MANAGE_SCHOOL_SELECT_FAILED
}
